CREATE DATABASE springmybatis;

USE springmybatis;

CREATE TABLE student
(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	GENDER VARCHAR(10) NOT NULL,
	HOBBIES VARCHAR(50) NOT NULL,
	COUNTRY VARCHAR(40) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL
)